import { z } from "zod";

const envSchema = z.object({
  HOST: z.string().default("0.0.0.0"),
  PORT: z.coerce.number().int().positive().default(8080),
  NODE_ENV: z.string().default("development"),
  JOB_COMPLETE_AFTER_MS: z.coerce.number().int().nonnegative().default(1000),
  QUEUE_DRIVER: z.enum(["memory", "redis"]).default("memory"),
  REDIS_URL: z.string().default("redis://localhost:6379"),
  REDIS_JOB_TTL_SECONDS: z.coerce.number().int().positive().default(86400),
  TENANT_STORE_DRIVER: z.enum(["memory", "postgres"]).default("memory"),
  DATABASE_URL: z.string().default("postgres://wp_rocket:wp_rocket@localhost:5432/wp_rocket_backend"),
  SAAS_AUTH_REQUIRED: z.coerce.boolean().default(false),
  API_KEY_PEPPER: z.string().default("local-development-pepper"),
  START_WORKERS: z.coerce.boolean().default(true),
  QUEUE_ATTEMPTS: z.coerce.number().int().positive().default(2),
  QUEUE_BACKOFF_MS: z.coerce.number().int().nonnegative().default(5000),
  QUEUE_REMOVE_ON_COMPLETE_COUNT: z.coerce.number().int().positive().default(1000),
  QUEUE_REMOVE_ON_COMPLETE_AGE_SECONDS: z.coerce.number().int().positive().default(3600),
  QUEUE_REMOVE_ON_FAIL_AGE_SECONDS: z.coerce.number().int().positive().default(86400),
  WORKER_CONCURRENCY: z.coerce.number().int().positive().default(1),
  CPCSS_TIMEOUT_MS: z.coerce.number().int().positive().default(30000),
  CPCSS_FETCH_TIMEOUT_MS: z.coerce.number().int().positive().default(10000),
  CPCSS_MAX_CSS_BYTES: z.coerce.number().int().positive().default(2_000_000),
  CPCSS_DESKTOP_WIDTH: z.coerce.number().int().positive().default(1300),
  CPCSS_DESKTOP_HEIGHT: z.coerce.number().int().positive().default(900),
  CPCSS_MOBILE_WIDTH: z.coerce.number().int().positive().default(390),
  CPCSS_MOBILE_HEIGHT: z.coerce.number().int().positive().default(844),
  CPCSS_ALLOW_PRIVATE_NETWORKS: z.coerce.boolean().default(false),
  CPCSS_CHROMIUM_EXECUTABLE: z.string().optional(),
  RUCSS_TIMEOUT_MS: z.coerce.number().int().positive().default(30000),
  RUCSS_DESKTOP_WIDTH: z.coerce.number().int().positive().default(1300),
  RUCSS_DESKTOP_HEIGHT: z.coerce.number().int().positive().default(900),
  RUCSS_MOBILE_WIDTH: z.coerce.number().int().positive().default(390),
  RUCSS_MOBILE_HEIGHT: z.coerce.number().int().positive().default(844),
  RUCSS_ALLOW_PRIVATE_NETWORKS: z.coerce.boolean().default(false),
  RUCSS_CHROMIUM_EXECUTABLE: z.string().optional(),
  PERFORMANCE_TIMEOUT_MS: z.coerce.number().int().positive().default(30000),
  PERFORMANCE_DESKTOP_WIDTH: z.coerce.number().int().positive().default(1300),
  PERFORMANCE_DESKTOP_HEIGHT: z.coerce.number().int().positive().default(900),
  PERFORMANCE_ALLOW_PRIVATE_NETWORKS: z.coerce.boolean().default(false),
  PERFORMANCE_CHROMIUM_EXECUTABLE: z.string().optional(),
  REPORT_RETENTION_DAYS: z.coerce.number().int().positive().default(30),
  ADMIN_TOKEN: z.string().optional(),
});

export const env = envSchema.parse(process.env);
